# This file is AUTO GENERATED, DO NOT EDIT manually

target_include_directories(${TARGET} PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_adc.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_aes.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_cmpss_lite.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_common.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_core.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_crcp.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_dma.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_ecap.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_eqep.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_flashctl.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_flash.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_fri.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_gpio.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_keystorectl.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_mcan.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_mcpwm.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_pga.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_spgss.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_sysctl.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_timer.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_tinielite.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_unicomm.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_unicommi2cc.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_unicommi2ct.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_unicommspi.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_unicommuart.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_wwdt.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/dl_xbar.c)
