/* Standard C Library */
#include <stdbool.h>
#include <stddef.h>

/* TI Drivers */
#include <ti/devices/DeviceFamily.h>
#include <ti/log/Log.h>
#include <ti/log/LogSinkTraceLPF3.h>

/* Zephyr Kernel */
#include <zephyr/init.h>
#include <zephyr/drivers/pinctrl.h>
#if (DeviceFamily_PARENT == DeviceFamily_PARENT_CC23X0)
    #include <zephyr/dt-bindings/pinctrl/cc23x0-pinctrl.h>
#elif (DeviceFamily_PARENT == DeviceFamily_PARENT_CC27XX)
    #include <zephyr/dt-bindings/pinctrl/cc27xx-pinctrl.h>
#else
    #error "This ti_log_config.c file is only compatible with CC23X0 and CC27XX devices!"
#endif
#include <zephyr/sys/util.h>
#include <pinctrl_soc.h>

/*
 *  ======== Log Modules ========
 */

/* The application must define log modules using the `Log_MODULE_DEFINE`
 * macro to configure log routing and filtering. This macro creates a log
 * module instance and connects it to a specific log sink (transport layer).
 *
 * For example, the definition below creates the RCL (Radio Control Layer)
 * log module and configures it to use the LogSinkTraceLPF3 sink:
 *
 * `Log_MODULE_DEFINE(LogModule_RCL, ...)`
 *
 * The log module definition specifies:
 *  - Module name (LogModule_RCL in this example)
 *  - Log sink initialization (Log_MODULE_INIT_SINK_TRACELPF3)
 *  - Enabled log levels (Log_INFO enables info-level logs and higher)
 *  - Sink delegate functions (printfSingleton, bufSingleton)
 *  - Dynamic level configuration (NULL = disabled)
 *
 * Each log module must be defined exactly once in the application.
 * Libraries typically do not define modules themselves, leaving the
 * routing decisions to the application developer.
 *
 * After defining a module here, use `Log_MODULE_USE` at call sites
 * where `Log_printf()` is invoked with this module name.
 */
Log_MODULE_DEFINE(LogModule_RCL,
    Log_MODULE_INIT_SINK_TRACELPF3(0,
                                   Log_DEBUG | Log_VERBOSE | Log_INFO | Log_WARNING | Log_ERROR,
                                   LogSinkTraceLPF3_printfSingleton,
                                   LogSinkTraceLPF3_bufSingleton,
                                   NULL));

/*
 *  ======== LogSinkTraceLPF3 ========
 */

#define TRACE_CONFIG_MODE                                                         \
    (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_MODE_CPU_ONLY)                       \
         ? (LogSinkTraceLPF3_CONFIG_CHANNELS_CPU_ONLY)                            \
         : (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_MODE_RADIO_ONLY)              \
                ? (LogSinkTraceLPF3_CONFIG_CHANNELS_RADIO_ONLY)                   \
                : (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_MODE_CPU_RADIO)        \
                       ? (LogSinkTraceLPF3_CONFIG_CHANNELS_CPU_RADIO)             \
                       : 0U)))

#define TRACE_CONFIG_TIMESTAMP                                                    \
    ((IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_TIMESTAMP)                          \
          ? (LogSinkTraceLPF3_CONFIG_TIMESTAMP_ENABLED)                           \
          : (LogSinkTraceLPF3_CONFIG_TIMESTAMP_DISABLED)))

#define TRACE_CONFIG_PRESCALER                                                    \
    (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_PRESCALER_DIV1)                      \
         ? (LogSinkTraceLPF3_CONFIG_PRESCALER_DIV1)                               \
         : (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_PRESCALER_DIV2)               \
                ? (LogSinkTraceLPF3_CONFIG_PRESCALER_DIV2)                        \
                : (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_PRESCALER_DIV3)        \
                       ? (LogSinkTraceLPF3_CONFIG_PRESCALER_DIV3)                 \
                       : (IS_ENABLED(CONFIG_SIMPLELINK_LPF3_TRACE_PRESCALER_DIV4) \
                              ? (LogSinkTraceLPF3_CONFIG_PRESCALER_DIV4)          \
                              : 0U))))

/*
 *  In SimpleLink (non-Zephyr) builds, the config struct is generated by
 *  SysConfig and pinmuxing uses GPIO_setConfigAndMux(). This file replaces
 *  both of those for Zephyr.
 *
 *  For Zephyr, the tracer pin configuration is hardcoded below for LP_EM_CC2340R5:
 *   - DIO5 configured as LRFD6 (LRFD GPO index 6)
 *   - No pull resistor, normal I/O mode, input disabled
 *
 */

#define LRFD_TRACER_PIN_GPO_INDEX 6U

/* Active state: DIO05 configured as LRFD6 for RF operation */
static const pinctrl_soc_pin_t lrf_gpo_active[] = {
    {
        .pin = 5,
        .iofunc = DIO5_LRFD6,       /* PFUNC6: routes RFEGPO6 → Tracer */
        .iomode = IOC_NO_IOPULL | IOC_IOMODE_NORMAL | IOC_INPUT_DISABLE
    }
};

const LogSinkTraceLPF3_Config LogSinkTraceLPF3_config = {
    .tracerConfig  = TRACE_CONFIG_MODE | TRACE_CONFIG_TIMESTAMP | TRACE_CONFIG_PRESCALER,
    .lrfdTracerPin = LRFD_TRACER_PIN_GPO_INDEX,
    .tracerPinMux  = 0, /* unused in Zephyr */
    .tracerPin     = 0, /* unused in Zephyr */
};

/* The LogSinkTraceLPF3_configPinMux() function configures the pinmux settings for the tracer
 * pin. The default weak definition uses TI's GPIO driver API. This strong definition overrides
 * it for Zephyr, using the Zephyr pinctrl API to configure the tracer pin according to the
 * lrf_gpo_active array settings.
 */
void LogSinkTraceLPF3_configPinMux(void)
{
    pinctrl_configure_pins(lrf_gpo_active, ARRAY_SIZE(lrf_gpo_active), PINCTRL_REG_NONE);
}

/* The LogSinkTraceLPF3_init() function has a void return type, which is incompatible
 * with Zephyr's SYS_INIT macro. All initialization functions registered with SYS_INIT
 * must return an int status code to indicate success or failure to the kernel.
 *
 * This wrapper function calls LogSinkTraceLPF3_init() and returns 0 to explicitly
 * signal successful initialization to the Zephyr kernel, even though LogSinkTraceLPF3_init()
 * is expected to always succeed.
 */
int LogSinkTraceLPF3_init_wrapper(void)
{
    LogSinkTraceLPF3_init();

    return 0;
}

/* Register the tracer initialization function with the Zephyr kernel to be called
 * during the POST_KERNEL phase, after kernel initialization but before the application
 * starts. CONFIG_KERNEL_INIT_PRIORITY_DEVICE ensures LogSinkTraceLPF3 initialization
 * occurs after TI power management initialization.
 */
SYS_INIT(LogSinkTraceLPF3_init_wrapper, POST_KERNEL, CONFIG_KERNEL_INIT_PRIORITY_DEVICE);
